package com.bndrs.voice.vo;

public class NetdiskResourceEntityVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.title
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.type
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.size
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.share_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String shareDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.share_id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String shareId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.share_name
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String shareName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.download_number
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private Integer downloadNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.created_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.updated_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.status
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column netdisk_resource.password
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.url
     *
     * @return the value of netdisk_resource.url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.url
     *
     * @param url the value for netdisk_resource.url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.id
     *
     * @return the value of netdisk_resource.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.id
     *
     * @param id the value for netdisk_resource.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.title
     *
     * @return the value of netdisk_resource.title
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.title
     *
     * @param title the value for netdisk_resource.title
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.type
     *
     * @return the value of netdisk_resource.type
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.type
     *
     * @param type the value for netdisk_resource.type
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.size
     *
     * @return the value of netdisk_resource.size
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.size
     *
     * @param size the value for netdisk_resource.size
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.share_date
     *
     * @return the value of netdisk_resource.share_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getShareDate() {
        return shareDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.share_date
     *
     * @param shareDate the value for netdisk_resource.share_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setShareDate(String shareDate) {
        this.shareDate = shareDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.share_id
     *
     * @return the value of netdisk_resource.share_id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getShareId() {
        return shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.share_id
     *
     * @param shareId the value for netdisk_resource.share_id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setShareId(String shareId) {
        this.shareId = shareId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.share_name
     *
     * @return the value of netdisk_resource.share_name
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getShareName() {
        return shareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.share_name
     *
     * @param shareName the value for netdisk_resource.share_name
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setShareName(String shareName) {
        this.shareName = shareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.download_number
     *
     * @return the value of netdisk_resource.download_number
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public Integer getDownloadNumber() {
        return downloadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.download_number
     *
     * @param downloadNumber the value for netdisk_resource.download_number
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setDownloadNumber(Integer downloadNumber) {
        this.downloadNumber = downloadNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.created_date
     *
     * @return the value of netdisk_resource.created_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.created_date
     *
     * @param createdDate the value for netdisk_resource.created_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.updated_date
     *
     * @return the value of netdisk_resource.updated_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.updated_date
     *
     * @param updatedDate the value for netdisk_resource.updated_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setUpdatedDate(String updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.status
     *
     * @return the value of netdisk_resource.status
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.status
     *
     * @param status the value for netdisk_resource.status
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column netdisk_resource.password
     *
     * @return the value of netdisk_resource.password
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column netdisk_resource.password
     *
     * @param password the value for netdisk_resource.password
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}