package com.bndrs.voice.dao;

import com.bndrs.voice.entity.FastsosoShareuserUrlEntity;
import com.bndrs.voice.example.FastsosoShareuserUrlEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FastsosoShareuserUrlEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int countByExample(FastsosoShareuserUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int deleteByExample(FastsosoShareuserUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int deleteByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int insert(FastsosoShareuserUrlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int insertSelective(FastsosoShareuserUrlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    List<FastsosoShareuserUrlEntity> selectByExample(FastsosoShareuserUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    FastsosoShareuserUrlEntity selectByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") FastsosoShareuserUrlEntity record, @Param("example") FastsosoShareuserUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByExample(@Param("record") FastsosoShareuserUrlEntity record, @Param("example") FastsosoShareuserUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByPrimaryKeySelective(FastsosoShareuserUrlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_shareuser_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByPrimaryKey(FastsosoShareuserUrlEntity record);
}