package com.bndrs.voice.dao;

import com.bndrs.voice.entity.FastsosoUrlEntity;
import com.bndrs.voice.example.FastsosoUrlEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FastsosoUrlEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int countByExample(FastsosoUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int deleteByExample(FastsosoUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int deleteByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int insert(FastsosoUrlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int insertSelective(FastsosoUrlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    List<FastsosoUrlEntity> selectByExample(FastsosoUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    FastsosoUrlEntity selectByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") FastsosoUrlEntity record, @Param("example") FastsosoUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByExample(@Param("record") FastsosoUrlEntity record, @Param("example") FastsosoUrlEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByPrimaryKeySelective(FastsosoUrlEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fastsoso_url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByPrimaryKey(FastsosoUrlEntity record);
}