package com.bndrs.voice.dao;

import com.bndrs.voice.entity.HotKeywordsEntity;
import com.bndrs.voice.example.HotKeywordsEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HotKeywordsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    int countByExample(HotKeywordsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    int deleteByExample(HotKeywordsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    int insert(HotKeywordsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    int insertSelective(HotKeywordsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    List<HotKeywordsEntity> selectByExample(HotKeywordsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") HotKeywordsEntity record, @Param("example") HotKeywordsEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot_keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    int updateByExample(@Param("record") HotKeywordsEntity record, @Param("example") HotKeywordsEntityExample example);
}