package com.bndrs.voice.dao;

import com.bndrs.voice.entity.NetdiskResourceEntity;
import com.bndrs.voice.example.NetdiskResourceEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetdiskResourceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int countByExample(NetdiskResourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int deleteByExample(NetdiskResourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int deleteByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int insert(NetdiskResourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int insertSelective(NetdiskResourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    List<NetdiskResourceEntity> selectByExample(NetdiskResourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    NetdiskResourceEntity selectByPrimaryKey(String url);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") NetdiskResourceEntity record, @Param("example") NetdiskResourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByExample(@Param("record") NetdiskResourceEntity record, @Param("example") NetdiskResourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByPrimaryKeySelective(NetdiskResourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table netdisk_resource
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByPrimaryKey(NetdiskResourceEntity record);
}