package com.bndrs.voice.dao;

import com.bndrs.voice.entity.ProxysEntity;
import com.bndrs.voice.example.ProxysEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProxysEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int countByExample(ProxysEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int deleteByExample(ProxysEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int insert(ProxysEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int insertSelective(ProxysEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    List<ProxysEntity> selectByExample(ProxysEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    ProxysEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProxysEntity record, @Param("example") ProxysEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByExample(@Param("record") ProxysEntity record, @Param("example") ProxysEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByPrimaryKeySelective(ProxysEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxys
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    int updateByPrimaryKey(ProxysEntity record);
}