package com.bndrs.voice.entity;

public class FastsosoShareuserUrlEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fastsoso_shareuser_url.url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fastsoso_shareuser_url.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fastsoso_shareuser_url.created_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fastsoso_shareuser_url.updated_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fastsoso_shareuser_url.status
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fastsoso_shareuser_url.url
     *
     * @return the value of fastsoso_shareuser_url.url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fastsoso_shareuser_url.url
     *
     * @param url the value for fastsoso_shareuser_url.url
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fastsoso_shareuser_url.id
     *
     * @return the value of fastsoso_shareuser_url.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fastsoso_shareuser_url.id
     *
     * @param id the value for fastsoso_shareuser_url.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fastsoso_shareuser_url.created_date
     *
     * @return the value of fastsoso_shareuser_url.created_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fastsoso_shareuser_url.created_date
     *
     * @param createdDate the value for fastsoso_shareuser_url.created_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fastsoso_shareuser_url.updated_date
     *
     * @return the value of fastsoso_shareuser_url.updated_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fastsoso_shareuser_url.updated_date
     *
     * @param updatedDate the value for fastsoso_shareuser_url.updated_date
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setUpdatedDate(String updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fastsoso_shareuser_url.status
     *
     * @return the value of fastsoso_shareuser_url.status
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fastsoso_shareuser_url.status
     *
     * @param status the value for fastsoso_shareuser_url.status
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}