package com.bndrs.voice.entity;

public class HotKeywordsEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords.id
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords.keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords.rank
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    private String rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords.created_date
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    private String createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords.updated_date
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    private String updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_keywords.status
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords.id
     *
     * @return the value of hot_keywords.id
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords.id
     *
     * @param id the value for hot_keywords.id
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords.keywords
     *
     * @return the value of hot_keywords.keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords.keywords
     *
     * @param keywords the value for hot_keywords.keywords
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords.rank
     *
     * @return the value of hot_keywords.rank
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords.rank
     *
     * @param rank the value for hot_keywords.rank
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public void setRank(String rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords.created_date
     *
     * @return the value of hot_keywords.created_date
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords.created_date
     *
     * @param createdDate the value for hot_keywords.created_date
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords.updated_date
     *
     * @return the value of hot_keywords.updated_date
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public String getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords.updated_date
     *
     * @param updatedDate the value for hot_keywords.updated_date
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public void setUpdatedDate(String updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_keywords.status
     *
     * @return the value of hot_keywords.status
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_keywords.status
     *
     * @param status the value for hot_keywords.status
     *
     * @mbggenerated Fri Mar 29 00:29:34 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}