package com.bndrs.voice.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ProxysEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.ip
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.port
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.types
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private Integer types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.protocol
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private Integer protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.country
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.area
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.updatetime
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.speed
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private BigDecimal speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proxys.score
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.id
     *
     * @return the value of proxys.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.id
     *
     * @param id the value for proxys.id
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.ip
     *
     * @return the value of proxys.ip
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.ip
     *
     * @param ip the value for proxys.ip
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.port
     *
     * @return the value of proxys.port
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.port
     *
     * @param port the value for proxys.port
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.types
     *
     * @return the value of proxys.types
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public Integer getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.types
     *
     * @param types the value for proxys.types
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setTypes(Integer types) {
        this.types = types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.protocol
     *
     * @return the value of proxys.protocol
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public Integer getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.protocol
     *
     * @param protocol the value for proxys.protocol
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setProtocol(Integer protocol) {
        this.protocol = protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.country
     *
     * @return the value of proxys.country
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.country
     *
     * @param country the value for proxys.country
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.area
     *
     * @return the value of proxys.area
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.area
     *
     * @param area the value for proxys.area
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.updatetime
     *
     * @return the value of proxys.updatetime
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.updatetime
     *
     * @param updatetime the value for proxys.updatetime
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.speed
     *
     * @return the value of proxys.speed
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public BigDecimal getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.speed
     *
     * @param speed the value for proxys.speed
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setSpeed(BigDecimal speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxys.score
     *
     * @return the value of proxys.score
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxys.score
     *
     * @param score the value for proxys.score
     *
     * @mbggenerated Wed Mar 27 17:31:00 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}